### ISSUE TITLE
Include in Gradle Plugin Repository

### ISSUE THREAD

**Issue by passy** [passy/build-time-tracker-plugin#37]
As of Gradle 2.1, there is a central repository of plugins at http://plugins.gradle.org/. There is also an easier way to add them to a build.gradle:

``` groovy
plugins {
    id 'com.company.myplugin' version '1.3'
}
```

Instructions for adding to that repostiory: http://plugins.gradle.org/submit.

**Comment by vanta** [comment]
Any update here?

**Comment by ctmay4** [comment]
Is there any thought on supporting this?  All my projects use the "new" style and plugin repository so it makes this plugin unusable since the two cannot be mixed and matched.

**Comment by passy** [comment]
Sorry that this took so ridiculously long, but it's finally up on the Gradle plugin repo. 

https://plugins.gradle.org/plugin/net.rdrei.android.buildtimetracker
