### ISSUE TITLE
Every time, clean project Build Time today resets...

### ISSUE THREAD

**Issue by druidamix** [passy/build-time-tracker-plugin#56]
Hi,

The plugin is interesting.

However, if one cleans the project total day resets.
It's one of the interesting features. 

Can you look at it?

Thanks

Using android studio 2.0 beta 3.

**Comment by passy** [comment]
> However, if one cleans the project total day resets.

How do you clean the project?

**Comment by druidamix** [comment]
Build -> clean project

**Comment by passy** [comment]
Sorry, but this is not enough information to help. You are in complete control of where the build information is stored. It seems like your build config cleans the full `build/` directory. Store the state somewhere else, and you should be fine.
