### ISSUE TITLE
Unable to delete file: xxx\build\times.csv

### ISSUE THREAD

**Issue by xiongwei-git** [passy/build-time-tracker-plugin#59]
On Windows platforms，execute "gradlew clean"

C:xx>gradlew clean
Incremental java compilation is an incubating feature.
:clean FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':clean'.
> Unable to delete file: xxx\build\times.csv

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by passy** [comment]
What's the stacktrace? Are there any special permissions on the file?
