### ISSUE TITLE
Output not displayed by default

### ISSUE THREAD

**Issue by adamdougal** [passy/build-time-tracker-plugin#66]
Looks like my previous PR #63 has not had the desired effect. Now the build time summary does not get logged unless you pass the `--info` flag rather then just disabling it for the quiet level. So I think that commit may need to be reverted unless you have any other ideas on how to log it out by default, just not  at quiet level.

**Comment by passy** [comment]
Hm, thanks for raising this. I'll revert it for now. I'm not sure if there's a way to configure it dynamically in the way you describe.

**Comment by adamdougal** [comment]
Np, sorry for introducing a bug!

**Comment by Tagakov** [comment]
Can you please revert this PR and update version in maven?

**Comment by passy** [comment]
@Tagakov Unfortunately I can't. Some of the tests turned out to be non-deterministic and fail randomly. I need to get those fixed first. I suggest using a previous version until then.

**Comment by passy** [comment]
Okay, tests are fixed now. I'll try to cut a new release tonight.

**Comment by adamdougal** [comment]
Looks like this is working now! Cheers
