### ISSUE TITLE
CSVSummaryReporter pukes on headers

### ISSUE THREAD

**Issue by jensck** [passy/build-time-tracker-plugin#71]
It would be nice if `CSVSummaryReporter` didn't puke when headers were enabled in the csv reporter.

I should be able to take the same csv file which feeds the csv summary reporter and open it in Excel (or some other tool) with a row of headers, so I know what the fields are without having to know it off the top of my head.

(Bonus points: don't repeat the headers when appending to the csv file either!)

**Comment by passy** [comment]
This should be fixed now. Release coming soon.
