### ISSUE TITLE
Report does not look like the readme

### ISSUE THREAD

**Issue by jaredsburrows** [passy/build-time-tracker-plugin#73]
## Config:

```
buildtimetracker {
  reporters {
    summary {
      ordered false
      threshold 50
      barstyle "ascii"
    }
  }
}
```
## Output:

```
BUILD SUCCESSFUL

Total time: 34.38 secs
== Build Time Summary ==
                                        1% :clean (0:00.244)
                                        1% :prepareComAndroidS?ompatV72421Library (0:00.175)
                                        2% :mergeDebugResources (0:00.580)
                                        1% :processDebugResources (0:00.305)
                                   ???  7% :compileDebugJavaWithJavac (0:02.360)
                                    ??  6% :lintDebug (0:01.939)
                                        0% :transformClassesWithJacocoForDebug (0:00.077)
                                        1% :transformClassesWi?etrolambdaForDebug (0:00.399)
?????????????????????????????????????? 76% :transformClassesWithDexForDebug (0:25.256)
                                        1% :packageDebug (0:00.368)
                                     ?  4% :countDebugDexMethods (0:01.286)

== BUILD SUCCESSFUL ==
```
## Config:

```
buildtimetracker {
  reporters {
    summary {
      ordered false
      threshold 50
      barstyle "unicode"
    }
  }
}
```
## Output:

```
BUILD SUCCESSFUL

Total time: 6.796 secs
== Build Time Summary ==
?????????????????????????????????????? 57% :compileDebugJavaWithJavac (0:03.122)
                         ????????????? 19% :lintDebug (0:01.056)
                        ?????????????? 22% :countDebugDexMethods (0:01.186)

== BUILD SUCCESSFUL ==
```

**Comment by passy** [comment]
Thanks for the report, it's not quite clear to me what is wrong. Do you see actual question marks on your screen? Can you give me information about your system and terminal?

**Comment by jaredsburrows** [comment]
@passy Yeah. It does not look nice and fancy like your README.me, it shows `?` instead of the "dark squares".

**Comment by passy** [comment]
And the second question? :)

**Comment by jaredsburrows** [comment]
I am using a Mac. Do you think it is a bashrc setting that is causing the UTF characters not showing up correctly?

**Comment by jaredsburrows** [comment]
Any update?

**Comment by passy** [comment]
@jaredsburrows Which terminal are you using?

**Comment by jaredsburrows** [comment]
@passy Just the normal mac terminal using bash.

**Comment by passy** [comment]
Tried to repro it with `Terminal.app` in its vanilla config with SF Mono Regular (11pt) and it seems to look okay:

![screenshot 2017-11-04 16 06 54](https://user-images.githubusercontent.com/9906/32407039-6ce7bb5c-c17a-11e7-91c5-788ab074ce78.png)

**Comment by jaredsburrows** [comment]
Im trying to reproduce this now.

I applied the plugin to https://github.com/jaredsburrows/android-gif-example and it didn't print anything out. Does I have to use the extension?

**Comment by passy** [comment]
@jaredsburrows I don't think I follow.

**Comment by jaredsburrows** [comment]
@passy I was saying that this plugin does not work without using the extension. Maybe set default values so users to not need to apply/use the extensions block?

Luckily, I was not able to repro this bug anymore:

```
40 actionable tasks: 30 executed, 10 up-to-date
== CSV Build Time Summary ==
Build time today: 0:02.034
Total build time: 0:02.034
(measured since moments ago)
== Build Time Summary ==
▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 95% :lintDebug (0:01.930)
```
