### ISSUE TITLE
Change log level of the summary reporter (or provide any other way to skip plugin execution)

### ISSUE THREAD

**Issue by Nirvanchik** [passy/build-time-tracker-plugin#80]
We want some way to skip plugin output for some of our tasks.

We get "== Build Time Summary ==" line when we run our special task with "-q" argument (QUIET only logging), and we don't want it. Changing log level to LIFECYCLE or any other level for summary reporter would work fine for us. But other people may want to stay with QUIET, so what about adding a special variable which would allow customizing log level?

**Comment by passy** [comment]
@Nirvanchik That's a good point. `-q` should certainly disable the output. Would you be interested in contributing a pull request for this?

**Comment by Nirvanchik** [comment]
Not sure I'll do this in my primary work time (we already fixed this by stripping extra lines from gradle output), but I'll try to do in my free time.
