### ISSUE TITLE
JDK 1.7 incompatibility

### ISSUE THREAD

**Issue by prageethintuit** [passy/build-time-tracker-plugin#91]
When using the latest version (0.11.0) with the bug fixes, and running in JDK 1.7, the following error is thrown in jenkins:

```
java.lang.UnsupportedClassVersionError: net/rdrei/android/buildtimetracker/BuildTimeTrackerPlugin : Unsupported major.minor version 52.0
```

This is because the artifact was compiled in JDK 1.8 in maven.

**Possible solution:**
 
Add the compatibility to the POM using build.gradle:
https://www.mkyong.com/maven/how-to-tell-maven-to-use-java-8/

Looking at the project, this seems to be handled in the `build.gradle` file and would need modification there.

Thanks for the great plugin!

**Comment by prageethintuit** [comment]
Hi @passy, it this something you'd be able to look at anytime soon? Thanks

**Comment by passy** [comment]
Hey @prageethintuit, sorry but I won't have time to look into this. Happy to review PRs for this, but I won't be able to explore this myself.

**Comment by prageeth** [comment]
@passy Please see https://github.com/passy/build-time-tracker-plugin/pull/93

**Comment by prageeth** [comment]
@passy Thanks for merging the request. Would you be able to release a patch or minor version please? Cheers! :)

**Comment by passy** [comment]
Sorry this took so long. Gradle threw some fun NPEs in my face when trying to sign the artifacts. `0.11.1` is up including the change.

**Comment by prageethintuit** [comment]
@passy `0.11.1` doesn't seem to be up on maven central yet. Please see:
![Maven Version](https://img.shields.io/maven-central/v/net.rdrei.android.buildtimetracker/gradle-plugin.svg?maxAge=2592000)
http://central.maven.org/maven2/net/rdrei/android/buildtimetracker/gradle-plugin/

**Comment by prageethintuit** [comment]
@passy Would this be something that can be looked at by next week? Cheers!

**Comment by passy** [comment]
@prageethintuit I'll give it one more try to get this release actually out of the staging area in Maven Central. The tooling is so disastrously terrible that I have no idea whether it will be fruitful this time or not. It took me 3 attempts to log in this time to not receive a `400` and another half-dozen to get the staging list to load.

I should probably just migrate this to Bintray to get the release process to work reliably.

**Comment by prageethintuit** [comment]
@passy Thanks for sorting this out, it seems to have worked 👍
