### ISSUE TITLE
[Question] Build Time of Plugin itself

### ISSUE THREAD

**Issue by avalanchas** [passy/build-time-tracker-plugin#97]
This might be a silly question but... Does this plugin itself slow down the build process noticeably?

**Comment by passy** [comment]
Not the build process itself, for sure. It doesn't have the opportunity to do that based on the hooks it uses. However, there is still the remaining issue https://github.com/passy/build-time-tracker-plugin/issues/70 of the logs being "funbounded" if you use the append option which can cause the exit times to increase over time.
